### ISSUE TITLE
/me route not working

### ISSUE THREAD

**Issue by solcanmihai** [andreigasparovici/cerc-info#18]
Server throws a long error.

**Comment by andreigasparovici** [comment]
Can you state the error here? I tried the route and it worked fine.

**Comment by solcanmihai** [comment]
node_1   | GET /api/me - - ms - -
node_1   | GET /api/groups/1/lessons 403 0.784 ms - 40
node_1   | OPTIONS /api/me 200 0.296 ms - 8
node_1   | (node:32) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'groupId' of undefined
node_1   |     at router.get (/usr/src/app/api/routes/me.js:32:37)
node_1   |     at <anonymous>
node_1   |     at process._tickCallback (internal/process/next_tick.js:188:7)
node_1   | (node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)

**Comment by andreigasparovici** [comment]
Since the users are added from a script, it may be possible that the user does not belong to any group, so it throws an error.

**Comment by solcanmihai** [comment]
Removed all images and containers from docker. Rebuilding everything. I'll be back soon.

**Comment by solcanmihai** [comment]
#19
