### ISSUE TITLE
/me new expected behaviour

### ISSUE THREAD

**Issue by solcanmihai** [andreigasparovici/cerc-info#19]
After rebuild, `\me` is working only on the teacher and student account. Not working on admin. Admins should not belong to any group, and because of that, groupId is undefined, and the server crashes. Also, if a user (teacher/student) is not in a group, the api should return an error like "User not in a group", instead of the server crashing. So the errors I was getting earlier were because the users didn't belong to a group.

**Comment by andreigasparovici** [comment]
That makes perfect sense. I'll patch that soon.

**Comment by andreigasparovici** [comment]
This will be patched after #14 and #22.

**Comment by andreigasparovici** [comment]
Outdated.
