### ISSUE TITLE
Teacher that belongs to multiple groups

### ISSUE THREAD

**Issue by solcanmihai** [andreigasparovici/cerc-info#22]
To make everything easier for everyone, if we want to implement this feature, there should be an option in the account settings, where to specify the active group, and all the content inside the app will be displayed for that group. If the teacher wants to add content to anther group, he just has to switch the active group from the settings. Is this a good ideea?

**Comment by andreigasparovici** [comment]
This and #14 should make one single issue.

**Comment by andreigasparovici** [comment]
Deadline: 8 aug

**Comment by solcanmihai** [comment]
This should be done only after all other features are working.
